version: '3'

volumes:
    wpdata:
        driver: local
        driver_opts:
          type: none
          o: bind
          device: /home/kamanfo/data/wordpress
    mbdata:
        driver: local
        driver_opts:
          type: none
          o: bind
          device: /home/kamanfo/data/mbdata

services:
    mariadb:
        build: srcs/requirements/mariadb
        container_name: mariadb
        restart: always
        expose:
            - "3306"
        volumes:
          - mbdata:/var/lib/mysql
        networks:
            - intra
        tty: true
    wordpress:
        build: srcs/requirements/wordpress
        container_name: wordpress
        restart: always
        volumes:
            - wpdata:/var/www/html
        expose: 
            - "9000"
        networks:
            - intra
        tty: true
        environment:
            DOMAIN_NAME:      ${DOMAIN_NAME}
            WP_TITLE:         ${WP_TITLE}
            WP_ADMIN_NAME:     ${WP_ADMIN_NAME}
            WP_ADMIN_PWD:     ${WP_ADMIN_PWD}
            WP_ADMIN_EMAIL:   ${WP_ADMIN_EMAIL}
            WP_USR:           ${WP_USR}
            WP_PWD:           ${WP_PWD}
            WP_EMAIL:         ${WP_EMAIL}
    
    nginx:
        build: srcs/requirements/nginx
        container_name: nginx
        restart: always
        ports:
            - "443:443"
        volumes:
            - wpdata:/var/www/html
        networks:
            - intra
        tty: true
networks:
    intra:
        driver: bridge
