version: '3'

volumes:
    data: {}
services:
    nginx:
        build: srcs/requirements/nginx/
        container_name: "nginx" 
        restart: always
        expose:
            - "443"
        ports:
            - "1024:443"
        volumes:
            - nginx:/etc/nginx/conf.d
            - data:/var/www/html
        networks:
            - intra
        tty: true
    mariadb:
        build: srcs/requirements/mariadb/
        container_name: "mariadb" 
        restart: always
        expose:
            - "3306:3306"
        networks:
            - intra
        tty: true
    wordpress:
        build: srcs/requirements/wordpress/
        #image: debian:buster
        container_name: "wordpress" 
        restart: always
        environment:
            MYSQL_HOST:       ${MYSQL_HOST}
            WP_DATABASE_NAME: ${WP_DATABASE_NAME}
            WP_DATABASE_USR:  ${WP_DATABASE_USR}
            WP_DATABASE_PWD:  ${WP_DATABASE_PWD}
            DOMAIN_NAME:      ${DOMAIN_NAME}
            WP_TITLE:         ${WP_TITLE}
            WP_ADMIN_USR:     ${WP_ADMIN_USR}
            WP_ADMIN_PWD:     ${WP_ADMIN_PWD}
            WP_ADMIN_EMAIL:   ${WP_ADMIN_EMAIL}
            WP_USR:           ${WP_USR}
            WP_PWD:           ${WP_PWD}
            WP_EMAIL:         ${WP_EMAIL}

        volumes:
            - data:/var/www/html
        expose: 
            - "9000:9000"
        networks:
            - intra
        tty: true
networks:
    intra:
        driver: bridge
