version: '3'

volumes:
    data: {}
services:
    nginx:
        build: srcs/requirements/nginx/
        container_name: "nginx" 
        restart: always
        expose:
            - "443"
        ports:
            - "443:443"
        volumes:
            - data:/var/www/html
        networks:
            - intra
        tty: true
    mariadb:
        build: srcs/requirements/mariadb/
        container_name: "mariadb" 
        restart: always
        expose:
            - "3306"
        networks:
            - intra
        tty: true
    wordpress:
        build: srcs/requirements/wordpress/
        #image: debian:buster
        container_name: "wordpress" 
        restart: always
        volumes:
            - data:/var/www/html
        expose: 
            - "9000"
        networks:
            - intra
        tty: true
networks:
    intra:
        driver: bridge
